// <auto-generated />
using System;
using BankAgreements.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankAgreements.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513131745_AddMaxInstallmentsToInstitution")]
    partial class AddMaxInstallmentsToInstitution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankAgreements.Infrastructure.Entities.Agreements.Agreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_agreements");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_agreements_contract_id");

                    b.ToTable("agreements", (string)null);
                });

            modelBuilder.Entity("BankAgreements.Infrastructure.Entities.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contract_number");

                    b.Property<Guid>("DebtorId")
                        .HasColumnType("uuid")
                        .HasColumnName("debtor_id");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("DebtorId")
                        .HasDatabaseName("ix_contracts_debtor_id");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("ix_contracts_institution_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("BankAgreements.Infrastructure.Entities.Debtors.Debtor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Documents")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documents");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_debtors");

                    b.ToTable("debtors", (string)null);
                });

            modelBuilder.Entity("BankAgreements.Infrastructure.Entities.Installments.Installment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgreementId")
                        .HasColumnType("uuid")
                        .HasColumnName("agreement_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean")
                        .HasColumnName("paid");

                    b.HasKey("Id")
                        .HasName("pk_installments");

                    b.HasIndex("AgreementId")
                        .HasDatabaseName("ix_installments_agreement_id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_installments_contract_id");

                    b.ToTable("installments", (string)null);
                });

            modelBuilder.Entity("BankAgreements.Infrastructure.Entities.Institutions.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("MaxInstallments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12)
                        .HasColumnName("max_installments");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_institutions");

                    b.ToTable("institutions", (string)null);
                });

            modelBuilder.Entity("BankAgreements.Infrastructure.Entities.Agreements.Agreement", b =>
                {
                    b.HasOne("BankAgreements.Infrastructure.Entities.Contracts.Contract", "Contract")
                        .WithMany("Agreements")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agreements_contracts_contract_id");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BankAgreements.Infrastructure.Entities.Contracts.Contract", b =>
                {
                    b.HasOne("BankAgreements.Infrastructure.Entities.Debtors.Debtor", "Debtor")
                        .WithMany()
                        .HasForeignKey("DebtorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_debtors_debtor_id");

                    b.HasOne("BankAgreements.Infrastructure.Entities.Institutions.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_institutions_institution_id");

                    b.Navigation("Debtor");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("BankAgreements.Infrastructure.Entities.Installments.Installment", b =>
                {
                    b.HasOne("BankAgreements.Infrastructure.Entities.Agreements.Agreement", "Agreement")
                        .WithMany("Installments")
                        .HasForeignKey("AgreementId")
                        .HasConstraintName("fk_installments_agreements_agreement_id");

                    b.HasOne("BankAgreements.Infrastructure.Entities.Contracts.Contract", "Contract")
                        .WithMany("Installments")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("fk_installments_contracts_contract_id");

                    b.Navigation("Agreement");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BankAgreements.Infrastructure.Entities.Agreements.Agreement", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("BankAgreements.Infrastructure.Entities.Contracts.Contract", b =>
                {
                    b.Navigation("Agreements");

                    b.Navigation("Installments");
                });
#pragma warning restore 612, 618
        }
    }
}
